eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
#ribbon:
#  eureka:
#    enable: true
feign:
  hystrix:
    enabled: true
server:
  port: 8765
spring:
  application:
    name: service-feign