server:
  port: 8761
spring:
  profiles: peer1
eureka:
  instance:
    hostname: peer1
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8769/eureka/
    register-with-eureka: false
    fetch-registry: false